version: "3.8"

services:
    bot:
        build:
            context: ../
            dockerfile: build/bot/Dockerfile
        restart: always
        environment:
            CONFIGS_APP: /app/configs/bot.yaml
            TELEGRAM_APITOKEN: ${TELEGRAM_APITOKEN}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 6062:6060
