// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// GetSpotParams defines parameters for GetSpot.
type GetSpotParams struct {
	// Usdt maximum number of USDT
	Usdt float32 `form:"usdt" json:"usdt"`

	// Spread minimum spread of deal
	Spread float32 `form:"spread" json:"spread"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// transaction
	// (GET /spot)
	GetSpot(ctx echo.Context, params GetSpotParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSpot converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpot(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpotParams
	// ------------- Required query parameter "usdt" -------------

	err = runtime.BindQueryParameter("form", true, true, "usdt", ctx.QueryParams(), &params.Usdt)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter usdt: %s", err))
	}

	// ------------- Required query parameter "spread" -------------

	err = runtime.BindQueryParameter("form", true, true, "spread", ctx.QueryParams(), &params.Spread)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter spread: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpot(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/spot", wrapper.GetSpot)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xU3WrbTBB9lWWuhb3+PgJFd00bSghNoHEKpQQxlsbWxt6fzI6SiOB3Lyslra2oTtqr",
	"XlnWnj8dpPMIxi095I9QUSzZBDHeQQ4rElWhoFqyt8oir0nUvZFaLSiKEkYXsezAGYiRDUEOX04u5yoS",
	"3xGrpWcVS0zHd8SxV51N9ETDNgMfyGEwkMP/Ez2ZQQYBpY4pxzQGL+liRTKeaySBD8SYrk8ryOETyWUS",
	"SaqMloQ4Qv59qGXxwdjGKtfYBbHyS3V1+XEOGZh0etsQt5CBQ5uerYlVEmS6bQxTBblwQxnEsiaLKSc9",
	"oA2phpnWOgNpQ6L12rDdZi/cjevcY2DCKrlXhJvfuPegN/q/NL9OxBi8i9R1/J/W6af0Tsh1LWMIG1N2",
	"FU5vYgr4uKNthGxHDJyaFtPLvI/rC66ID0ACm5L24unJ0YuAGdwW0g5bHCnx+Y5f3FAp8OsGMmOb/h+b",
	"6p/LhNY3TgqM68I/Z9sRHbF+YixM9YeM0hu3Bz7So+i4Lkof5dXHyyBleCO0rHHgDl9Pzi8+w09sFDZu",
	"lbD9pBRpXvYZx9+OT+cHGOL38WdXZxen52OEp4/m8LeRQWztwm8GIeYfxhTTABYV432xpOEbpPWYeGJ0",
	"BIsPr6/ELn7Q5Owv3rwE2R8dNqta1PMWdBqxsRa5hRx2J7Xj9lPeT2fDG8ihFgn5dNof5O+01rC93v4I",
	"AAD//1TxVOxFBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
