log_to_file: false
debug: true

postgres:
 host_local: localhost
 host_remote: postgres
 port: 5432

endpoint:
 spot_local: http://localhost:8080/spot
 spot_remote: http://host.docker.internal:8080/spot